[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = true
enableXsrfProtection = true

[theme]
primaryColor = "#0C3A6D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F5FA"
textColor = "#333333"
font = "sans serif"
